version: '3.8'

services:

  api:
    build: ./server
    ports:
      - "3000:3000"
    env_file: "./server/.env"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - logs:/usr/src/app/logs

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      start_period: 30s
      start_interval: 4s
      interval: 300s
      timeout: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"

volumes:
  db-data:
  logs:
