version: '3.8'

services:

  api:
    build: ./server
    ports:
      - "3000:3000"
    env_file: "server/.env"
    #environment:
    #  DB_HOST: db
    #  DB_USER: root
    #  DB_PASSWORD: rootpassword
    #  DB_NAME: mydb
    #  RQM_SERV: https://www.larouequimarche.ch/wp-admin/admin-ajax.php
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 2s
      retries: 100

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"

volumes:
  db-data:
